a=int(input())
b=int(input())
c=int(input())
if a>b and a>c and b>c: print('oldest '+str(a)+ ', amount '+str(b)+', youngest '+str(c))
elif a<b and a>c and b>c: print('oldest '+str(b)+ ', amount '+str(a)+', youngest '+str(c))
elif a<b and a<c and b<c: print('oldest '+str(c)+ ', amount '+str(a)+', youngest '+str(b))
elif a>b and a>c and b<c: print('oldest '+str(a)+ ', amount '+str(c)+', youngest '+str(b))
elif a<b and a<c and b>c: print('oldest '+str(b)+ ', amount '+str(c)+', youngest '+str(a))
elif a<b and a<c and b>c: print('oldest '+str(c)+ ', amount '+str(b)+', youngest '+str(a))